spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
